export declare const TokenService: {
  setAccessToken: (token: string) => void;
  getAccessToken: () => string | null;
  removeAccessToken: () => void;
  setAnonSessionId: (anonymousId: string) => void;
  getAnonSessionId: () => string | null;
  removeAnonSessionId: () => void;
  setLogin: (logeIn?: string) => void;
  getLogin: () => string | null;
  removeLogin: () => void;
  setCustomerVersion: (customerVersion: string) => void;
  setCustomerId: (customerId: string) => void;
  getCustomerId: () => string | null;
  getCustomerVersion: () => string | null;
  setCartId: (cartId: string) => void;
  setCartVersion: (cartVersion: string) => void;
  removeCartId: () => void;
  getCartId: () => string | null;
  getCartVersion: () => string | null;
  setRefreshToken: (token: string) => void;
  getRefreshToken: () => string | null;
  removeRefreshToken: () => void;
  clearTokens: () => void;
};
